services:

  trino:
    image: trinodb/trino:457
    ports:
      - "8080:8080"
    environment:
      - TRINO_PASSWORD_FILE=/etc/trino/password.db
    depends_on:
      - metastore_db
      - hive-metastore
      - minio
    volumes:
      - ./trino/etc/trino/catalog:/etc/trino/catalog
    networks:
      - datalake-network


  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - datalake-network


  airflow:
    container_name: airflow-container
    build:
      context: ./airflow
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      
    depends_on:
      - postgres
    networks:
      - datalake-network
    command: >
      bash -c "airflow db migrate && airflow standalone"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9001:9001
      - 9000:9000
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./minio/data:/data
    networks:
      - datalake-network

  metastore_db:
    image: postgres:11
    hostname: metastore_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    command: [ "postgres", "-c", "wal_level=logical" ]
    networks:
      - datalake-network


  hive-metastore:
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://warehouse/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: password
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
    depends_on:
      - metastore_db
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/9083"
    networks:
      - datalake-network

  # PostgreSQL para o Metabase
  postgres-metabase:
    image: postgres:13
    container_name: postgres-metabase
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase123
    volumes:
      - ./postgres-metabase/data:/var/lib/postgresql/data
    networks:
      - datalake-network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - 3000:3000
    environment:
      # Configuração para armazenar dados do Metabase no PostgreSQL
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase123
      - MB_DB_HOST=postgres-metabase
      # Configuração para conexão com o Trino (para consultas)
      - MB_TRINO_HOST=trino
      - MB_TRINO_PORT=8080
      - MB_TRINO_USER=trino
      - MB_TRINO_PASS=trino
    volumes:
      - ./metabase/data:/metabase-data
    depends_on:
      - postgres-metabase
      - trino
    networks:
      - datalake-network


volumes:
  airflow_data:
    driver: local
  postgres_data:
    driver: local

networks:
  datalake-network:
    name: trino-iceberg-hive-network  
